name: Terraform Workflow

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'terraform/**'
  issue_comment:
    types: [created]

jobs:
  terraform-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        id: terraform-init
        run: terraform init
        working-directory: ./terraform/environments/development

      - name: Terraform Plan development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        id: terraform-plan
        run: terraform plan
        working-directory: ./terraform/environments/development

      - name: Terraform Apply development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        working-directory: ./terraform/environments/development
